# Generated by Django 5.0.4 on 2024-04-22 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_type', models.CharField(choices=[('bheri', 'Bheri'), ('manakamana', 'Manakamana')], max_length=100)),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('Service_getter', models.TextField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('descriptions_address', models.TextField()),
                ('time_style', models.CharField(default='default', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asap', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
