# Generated by Django 5.0.4 on 2024-04-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gas',
            old_name='adress',
            new_name='address',
        ),
    ]
