# Generated by Django 5.0.4 on 2024-04-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0005_gas_status'),
        ('service', '0006_vender_service_odered_number_service_vender'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='odered_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gas',
            name='vender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vender'),
        ),
    ]
