# Generated by Django 5.0.4 on 2024-04-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_gas_odered_number_gas_vender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='odered_number',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
