# Generated by Django 5.0.4 on 2024-04-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0011_alter_gas_odered_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gas',
            name='odered_number',
        ),
    ]
