# Generated by Django 5.0.4 on 2024-04-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0012_remove_gas_odered_number'),
    ]

    operations = [
    ]
