# Generated by Django 5.0.4 on 2024-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0013_auto_20240426_1647'),
    ]

    operations = [
    ]
