# Generated by Django 5.0.4 on 2024-04-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0014_auto_20240426_1649'),
        ('service', '0007_alter_service_odered_number_thirduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='odered_number',
            field=models.CharField(default='2019309300', max_length=100),
        ),
        migrations.AlterField(
            model_name='gas',
            name='vender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.vender'),
        ),
    ]
