# Generated by Django 5.0.4 on 2024-04-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0015_gas_odered_number_alter_gas_vender'),
        ('service', '0012_alter_service_vender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='vender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vender'),
        ),
    ]
