# Generated by Django 5.0.4 on 2024-05-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_gathered_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Gathered_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Gathered_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Gathered_home_coordination',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Gathered_mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Gathered_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='alternativ_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_district',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_landmark',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_municipality',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_province',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_tole',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_wada',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_zipcode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='id_other',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_district',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_landmark',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_municipality',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_province',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_tole',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_wada',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_zipcode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='qualification',
        ),
        migrations.CreateModel(
            name='KycUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('alternativ_number', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, max_length=100, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_municipality', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_wada', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_tole', models.CharField(blank=True, max_length=200, null=True)),
                ('permanent_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('current_province', models.CharField(blank=True, max_length=200, null=True)),
                ('current_district', models.CharField(blank=True, max_length=100, null=True)),
                ('current_municipality', models.CharField(blank=True, max_length=200, null=True)),
                ('current_wada', models.CharField(blank=True, max_length=100, null=True)),
                ('current_tole', models.CharField(blank=True, max_length=200, null=True)),
                ('current_zipcode', models.CharField(blank=True, max_length=100, null=True)),
                ('current_landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('id_other', models.CharField(blank=True, max_length=100, null=True)),
                ('Gathered_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Gathered_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('Gathered_address', models.CharField(blank=True, max_length=100, null=True)),
                ('Gathered_home_coordination', models.CharField(blank=True, max_length=200, null=True)),
                ('Gathered_description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
