# Generated by Django 5.0.4 on 2024-04-16 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_info', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('descriptions', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.device')),
            ],
        ),
    ]
