# Generated by Django 5.0.4 on 2024-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_service_getter_service_asap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time_style',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
