# Generated by Django 5.0.4 on 2024-04-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_time_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('verified', 'Verified'), ('on_the_way', 'On_the_way'), ('delivered', 'Delivered'), ('cancell_user', 'Cancell_user'), ('cancell_admin', 'Cancell_admin')], default='ordered', max_length=100),
        ),
    ]
