# Generated by Django 5.0.4 on 2024-04-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_odered_number_thirduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='odered_number',
            field=models.CharField(default='2019309300', max_length=100),
        ),
    ]
