# Generated by Django 5.0.4 on 2024-04-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_odered_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='odered_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
