# Generated by Django 5.0.4 on 2024-04-30 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_service_vender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vender'),
        ),
    ]
