# Generated by Django 5.0.4 on 2024-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_service_vender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirduser',
            name='adress',
        ),
        migrations.AddField(
            model_name='thirduser',
            name='alternativ_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='landmark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='municipality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='tole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='wada',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='thirduser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
